#!/bin/bash
# Provision upload.jolkr.app on HestiaCP — DNS-only (grey-cloud) subdomain
# that bypasses Cloudflare's 100 MB body-size limit for >100 MB attachment uploads.
#
# What this script does:
#   1. Sanity check that upload.jolkr.app DNS resolves directly (not via CF).
#   2. v-add-web-domain phillipp upload.jolkr.app 192.168.178.20  (idempotent)
#   3. v-add-letsencrypt-domain phillipp upload.jolkr.app          (idempotent)
#   4. Install custom HestiaCP nginx proxy templates (jolkr-upload.tpl + .stpl)
#      that ONLY proxy the two attachment endpoints; everything else → 404.
#   5. Apply the proxy template to upload.jolkr.app and rebuild config.
#   6. nginx -t && systemctl reload nginx.
#
# Run on 192.168.178.20 as:
#   sudo bash ~/setup-upload-domain.sh
#
# Idempotent — safe to re-run after edits.

set -euo pipefail

USER="phillipp"
DOMAIN="upload.jolkr.app"
IP="192.168.178.20"
EXPECTED_PUBLIC_IP="212.45.36.41"
BACKEND_HOST="192.168.178.100"
TPL_NAME="jolkr-upload"
TPL_DIR="/usr/local/hestia/data/templates/web/nginx"

# ─────────────────────────────────────────────────────────────────
if [[ "$EUID" -ne 0 ]]; then
  echo "ERROR: must run as root. Use:  sudo bash $0"
  exit 1
fi

if [[ ! -x /usr/local/hestia/bin/v-add-web-domain ]]; then
  echo "ERROR: HestiaCP not found at /usr/local/hestia/"
  exit 1
fi

PATH=/usr/local/hestia/bin:$PATH

# ── 1/6 — DNS sanity check ───────────────────────────────────────
echo "=== 1/6 — DNS sanity check ============================================="
RESOLVED=$(getent hosts "$DOMAIN" | awk '{print $1}' | head -n1 || true)
if [[ -z "$RESOLVED" ]]; then
  echo "FATAL: $DOMAIN does not resolve. Cloudflare A-record missing or not propagated."
  exit 1
fi
echo "   $DOMAIN → $RESOLVED"
if [[ "$RESOLVED" != "$EXPECTED_PUBLIC_IP" ]]; then
  echo "   WARN: expected $EXPECTED_PUBLIC_IP (grey-cloud direct)."
  echo "         If this is a Cloudflare IP the record is still proxied (orange-cloud);"
  echo "         Let's Encrypt HTTP-01 challenge will likely fail and CF still caps at 100MB."
fi

# ── 2/6 — Add web domain ─────────────────────────────────────────
echo
echo "=== 2/6 — Add web domain ($DOMAIN) ====================================="
if v-list-web-domain "$USER" "$DOMAIN" >/dev/null 2>&1; then
  echo "   already exists — skipping"
else
  v-add-web-domain "$USER" "$DOMAIN" "$IP"
  echo "   added"
fi

# ── 3/6 — Issue Let's Encrypt cert ───────────────────────────────
echo
echo "=== 3/6 — Issue Let's Encrypt cert ====================================="
SSL_STATE=$(v-list-web-domain "$USER" "$DOMAIN" plain 2>/dev/null | awk -F: '/^SSL/ {print $2}' | tr -d ' ' || true)
if [[ "$SSL_STATE" == "yes" ]]; then
  echo "   SSL already enabled — skipping"
else
  v-add-letsencrypt-domain "$USER" "$DOMAIN"
  echo "   issued"
fi

# ── 4/6 — Install custom HestiaCP nginx proxy templates ──────────
echo
echo "=== 4/6 — Install custom proxy template '$TPL_NAME' ===================="
mkdir -p "$TPL_DIR"

# Port 80 — redirect everything to https (or serve /.well-known/ for ACME renewal).
cat > "$TPL_DIR/${TPL_NAME}.tpl" <<'TPLEOF'
#=========================================================================#
# Custom Jolkr upload template (port 80) — generated by setup-upload-domain.sh
#=========================================================================#
server {
    listen      %ip%:%web_port%;
    server_name %domain_idn% %alias_idn%;

    # ACME HTTP-01 renewal
    location ^~ /.well-known/acme-challenge/ {
        root /home/%user%/web/%domain%/public_html;
        try_files $uri =404;
    }

    # Everything else → https
    location / { return 301 https://$host$request_uri; }
}
TPLEOF

# Port 443 — strict allow-list of upload endpoints, proxy to backend.
cat > "$TPL_DIR/${TPL_NAME}.stpl" <<TPLEOF
#=========================================================================#
# Custom Jolkr upload template (port 443) — generated by setup-upload-domain.sh
# DO NOT EDIT BY HAND; re-run setup-upload-domain.sh to regenerate.
#=========================================================================#
server {
    listen      %ip%:%proxy_ssl_port% ssl;
    server_name %domain_idn% %alias_idn%;
    error_log   /var/log/apache2/domains/%domain%.error.log error;

    ssl_certificate     %ssl_pem%;
    ssl_certificate_key %ssl_key%;
    ssl_stapling        on;
    ssl_stapling_verify on;

    # Body limit — accommodates MAX_FILE_SIZE 250MB + multipart overhead.
    client_max_body_size 300M;
    client_body_buffer_size 128k;

    # Stream uploads directly to backend; no on-disk buffering.
    proxy_request_buffering off;

    # Long-running uploads (250MB on a slow connection).
    proxy_read_timeout 600;
    proxy_send_timeout 600;
    proxy_connect_timeout 30;

    include /home/%user%/conf/web/%domain%/nginx.hsts.conf*;

    # Lock down dotfiles.
    location ~ /\\.(?!well-known) { deny all; return 404; }

    # Allow ONLY the two attachment endpoints. Everything else → 404.
    # POST /api/channels/<uuid>/messages/<uuid>/attachments
    # POST /api/dms/<uuid>/messages/<uuid>/attachments
    location ~ ^/api/(channels|dms)/[a-zA-Z0-9-]+/messages/[a-zA-Z0-9-]+/attachments$ {
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_pass https://${BACKEND_HOST}\$request_uri;
    }

    # Hard-deny everything else; this subdomain is upload-only.
    location / { return 404; }
}
TPLEOF

chmod 644 "$TPL_DIR/${TPL_NAME}.tpl" "$TPL_DIR/${TPL_NAME}.stpl"
echo "   installed: $TPL_DIR/${TPL_NAME}.tpl"
echo "   installed: $TPL_DIR/${TPL_NAME}.stpl"

# ── 5/6 — Apply proxy template + rebuild ─────────────────────────
echo
echo "=== 5/6 — Apply proxy template + rebuild domain ========================"
v-change-web-domain-proxy-tpl "$USER" "$DOMAIN" "$TPL_NAME" || {
  echo "   v-change-web-domain-proxy-tpl failed — falling back to v-rebuild-web-domain"
  v-rebuild-web-domain "$USER" "$DOMAIN"
}

# ── 6/6 — Validate + reload nginx ────────────────────────────────
echo
echo "=== 6/6 — Validate + reload nginx ======================================"
if nginx -t; then
  systemctl reload nginx
  echo "   nginx reloaded"
else
  echo "FATAL: nginx -t failed. Generated config is broken; check above."
  exit 1
fi

# ── DONE ─────────────────────────────────────────────────────────
echo
echo "=== DONE ==============================================================="
echo "Domain:        https://$DOMAIN"
echo "Cert path:     /home/$USER/conf/web/$DOMAIN/ssl/$DOMAIN.pem"
echo "Active config: /home/$USER/conf/web/$DOMAIN/nginx.ssl.conf"
echo "Template:      $TPL_DIR/${TPL_NAME}.{tpl,stpl}  (survives v-rebuild-web-domain)"
echo
echo "Quick smoke test:"
echo "  curl -I https://$DOMAIN/                 # expect 404"
echo "  curl -I https://$DOMAIN/api/channels/x/messages/y/attachments  # expect 401 or 405 (auth/method) — NOT 404"
echo
echo "NEXT STEP: tell Claude this script ran successfully."
echo "           He'll then push the frontend / backend / Tauri changes."
