import { isTauri } from './detect';

// For Tauri builds, API requests go directly to the server.
// For web, they're proxied by nginx/vite.
// Users can override via localStorage (settings screen later).
const DEFAULT_SERVER = 'https://jolkr.app';

/** Whether the user can pick a custom server (dev machine only). */
export const isDevMachine = !!import.meta.env.VITE_DEV_MODE;

export function hasServerUrl(): boolean {
  if (!isTauri) return true; // web always uses relative URLs
  if (!isDevMachine) return true; // production: always use jolkr.app, no setup needed
  try {
    return !!localStorage.getItem('jolkr_server_url');
  } catch { return false; }
}

export function getServerUrl(): string {
  if (!isTauri) return '';
  try {
    const saved = localStorage.getItem('jolkr_server_url');
    if (saved && isValidServerUrl(saved)) return saved;
  } catch { /* ignore */ }
  return DEFAULT_SERVER;
}

/** Validate server URL: must be HTTPS (or localhost for dev) */
export function isValidServerUrl(url: string): boolean {
  try {
    const parsed = new URL(url);
    // Allow HTTPS always, HTTP only for localhost/dev
    if (parsed.protocol === 'https:') return true;
    if (parsed.protocol === 'http:' && (parsed.hostname === 'localhost' || parsed.hostname === '127.0.0.1')) return true;
    return false;
  } catch { return false; }
}

export function getApiBaseUrl(): string {
  if (isTauri) return `${getServerUrl()}/api`;
  // Vite dev server with local proxy
  if (import.meta.env.DEV && import.meta.env.VITE_API_TARGET === 'local') return '/api';
  // Vite dev without local backend → hit live server directly
  if (import.meta.env.DEV) return 'https://jolkr.app/api';
  // Production build: relative path (served by nginx)
  return '/api';
}

export function getWsUrl(): string {
  if (isTauri) {
    const server = getServerUrl();
    const wsProto = server.startsWith('https') ? 'wss' : 'ws';
    const host = server.replace(/^https?:\/\//, '');
    return `${wsProto}://${host}/ws`;
  }
  if (import.meta.env.DEV && import.meta.env.VITE_API_TARGET !== 'local') {
    return 'wss://jolkr.app/ws';
  }
  const proto = window.location.protocol === 'https:' ? 'wss:' : 'ws:';
  return `${proto}//${window.location.host}/ws`;
}

export function getMediaWsUrl(): string {
  if (isTauri) {
    const server = getServerUrl();
    const wsProto = server.startsWith('https') ? 'wss' : 'ws';
    // Media WS goes through nginx (port 80/443), not the API server (port 8080)
    const host = server.replace(/^https?:\/\//, '').replace(/:\d+$/, '');
    return `${wsProto}://${host}/media/ws/voice`;
  }
  if (import.meta.env.DEV && import.meta.env.VITE_API_TARGET !== 'local') {
    return 'wss://jolkr.app/media/ws/voice';
  }
  const proto = window.location.protocol === 'https:' ? 'wss:' : 'ws:';
  return `${proto}//${window.location.host}/media/ws/voice`;
}

export function getBasename(): string {
  return isTauri ? '/' : '/app';
}

/**
 * Build a shareable invite URL that always points at the SPA invite route.
 *
 * - Tauri desktop: `window.location.origin` is `tauri://localhost` and useless
 *   to recipients, so we hardcode the public host.
 * - Web (prod or dev): use the current origin so links work in dev/staging,
 *   and always include the `/app` SPA basename — without it the link hits
 *   the landing page instead of `<InviteAccept />`.
 */
export function buildInviteUrl(code: string): string {
  if (isTauri) return `https://jolkr.app/app/invite/${code}`;
  return `${window.location.origin}/app/invite/${code}`;
}

/** Try to extract an invite code from either a bare code or a full invite URL. */
export function parseInviteInput(raw: string): string {
  const trimmed = raw.trim();
  if (!trimmed) return '';
  // Match the last `/invite/<code>` segment (handles both /app/invite/CODE and /invite/CODE,
  // with or without trailing slash/query/hash).
  const match = trimmed.match(/\/invite\/([^/?#\s]+)/);
  if (match) return match[1];
  return trimmed;
}

/**
 * Rewrite internal MinIO URLs to go through the nginx /s3/ proxy.
 * Presigned URLs generated by the backend use the Docker-internal hostname
 * "minio:9000" which browsers can't reach. This replaces that with the
 * nginx proxy path (web) or direct localhost (Tauri desktop).
 */
export function rewriteStorageUrl(url: string | null | undefined): string | undefined {
  if (!url) return undefined;
  if (isTauri) {
    // Route through nginx /s3/ proxy — direct MinIO access fails because
    // presigned URLs are signed for Host "minio:9000", not "localhost:9000"
    const server = getServerUrl() || 'http://localhost';
    return url.replace(/^https?:\/\/minio:9000\//, `${server.replace(/:8080$/, '')}/s3/`);
  }
  if (import.meta.env.DEV && import.meta.env.VITE_API_TARGET !== 'local') {
    return url.replace(/^https?:\/\/minio:9000\//, 'https://jolkr.app/s3/');
  }
  return url.replace(/^https?:\/\/minio:9000\//, '/s3/');
}
